version: "3.3"
services:
  app:
    ports:
      - "80:5000" # change 80 to 443 if you need serve via 'https'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    restart: always
    image: ts-react-ssr-basis:latest
    build: .
